{ config, lib, pkgs, ui, ... }:

let
  cfg = config.my.wm;

  stripHash = s: lib.removePrefix "#" s;

  # Token colors (accept "#rrggbb" or "rrggbb")
  bg = stripHash ui.colors.background;
  fg = stripHash ui.colors.foreground;
  focus = stripHash ui.colors.focus;

  # ---- token-driven sizing ----
  s = ui.scale or 1.0;

  # integer rounding
  px = x: builtins.floor (x + 0.5);

  fontPx    = px (ui.monoFont.size * s);
  heightPx  = px (1.8 * fontPx);
  spacingPx = px (0.55 * fontPx);

  vPadPx    = px (0.20 * fontPx);
  hPadPx    = px (0.45 * fontPx);

  # Workspace buttons: thin, full bar height (vertical padding 0)
  wsHPadPx  = px (0.55 * fontPx);

  # ---- battery: hidden if absent ----
  batScript = pkgs.writeShellScript "waybar-bat" ''
    set -eu
    bat="$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -n1 || true)"
    [ -n "$bat" ] || exit 0
    cap="$(cat "$bat/capacity" 2>/dev/null || true)"
    [ -n "$cap" ] || exit 0
    printf 'BAT: %s%%\n' "$cap"
  '';
in
{
  config = lib.mkIf (cfg.enable && cfg.bar.enable && cfg.bar.backend == "waybar") {
    my.wm.bar.command = "waybar";

    home.packages = [ pkgs.waybar ];

    xdg.configFile."waybar/config".text = builtins.toJSON {
      layer = "top";
      position = cfg.bar.position;

      height = heightPx;
      spacing = spacingPx;

      modules-left = [ "sway/workspaces" ];
      modules-center = [ ];
      modules-right = [
        "network"
        "custom/bat"
        "disk"
        "memory"
        "clock"
      ];

      network = {
        interval = 2;
        format-wifi = "NET: WIFI";
        format-ethernet = "NET: ETH";
        format-disconnected = "NET: --";
        tooltip-format-wifi = "{essid} ({signalStrength}%)\n{ipaddr}";
        tooltip-format-ethernet = "{ifname}\n{ipaddr}";
        tooltip-format-disconnected = "disconnected";
      };

      "custom/bat" = {
        exec = "${batScript}";
        interval = 30;
        return-type = "plain";
        hide-empty-text = true;
        tooltip = false;
      };

      disk = {
        interval = 60;
        path = "/";
        format = "/: {used}/{total}";
        tooltip = false;
      };

      memory = {
        interval = 2;
        format = "MEM: {used}/{total}";
        tooltip = false;
      };

      clock = {
        interval = 30;
        format = "{:%a %F %H:%M}";
        tooltip = false;
      };
    };

    xdg.configFile."waybar/style.css".text = ''
      /* Generated by Home Manager */

      * {
        font-family: "${ui.monoFont.family}";
        font-size: ${toString fontPx}px;
        border: none;
        border-radius: 0;
        box-shadow: none;
        min-height: 0;
        padding: 0;
        margin: 0;
      }

      @define-color bg    #${bg};
      @define-color fg    #${fg};
      @define-color focus #${focus};

      window#waybar {
        background: @bg;
        color: @fg;
        padding: ${toString vPadPx}px ${toString hPadPx}px;
      }

      /* Workspaces: thin, full-height buttons */
      #workspaces {
        background: transparent;
      }

      #workspaces button {
        background: @bg;
        color: @fg;
        padding: 0 ${toString wsHPadPx}px;
      }

      #workspaces button.focused {
        background: @focus;
        color: @bg;
      }

      /* optional: keep hover consistent with focused */
      #workspaces button:hover {
        background: @focus;
        color: @bg;
      }

      /* RHS modules: keep them visually “flat” */
      #network, #custom-bat, #disk, #memory, #clock {
        padding: 0;
        margin: 0;
      }
    '';
  };
}
