
{ config, lib, pkgs, ui, ... }:

let
  cfg = config.my.wm;

  stripHash = s: lib.removePrefix "#" s;
  p = i: stripHash (builtins.elemAt ui.terminal.palette i);

  bg = stripHash ui.terminal.background;
  fg = stripHash ui.terminal.foreground;

  # ---- token-driven sizing ----
  s = ui.scale;

  # integer rounding
  px = x: builtins.floor (x + 0.5);

  fontPx    = px (ui.monoFont.size * s);
  heightPx  = px (1.8 * fontPx);
  spacingPx = px (0.55 * fontPx);
  vPadPx    = px (0.25 * fontPx);
  hPadPx    = px (0.45 * fontPx);

  # ---- battery that hides when absent ----
  batScript = pkgs.writeShellScript "waybar-bat" ''
    set -eu
    bat="$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -n1 || true)"
    [ -n "$bat" ] || exit 0
    cap="$(cat "$bat/capacity" 2>/dev/null || true)"
    [ -n "$cap" ] || exit 0
    printf 'BAT: %s%%\n' "$cap"
  '';
in
{
  config = lib.mkIf (cfg.enable && cfg.bar.enable && cfg.bar.backend == "waybar") {
    my.wm.bar.command = "waybar";

    home.packages = [ pkgs.waybar ];

    xdg.configFile."waybar/config".text = builtins.toJSON {
      layer = "top";
      position = cfg.bar.position;

      height = heightPx;
      spacing = spacingPx;

      modules-left = [ "sway/workspaces" ];
      modules-center = [ ];
      modules-right = [
        "network"
        "custom/bat"
        "disk"
        "memory"
        "clock"
      ];

      # --- NET ---
      network = {
        interval = 2;
        format-wifi = "NET: WIFI";
        format-ethernet = "NET: ETH";
        format-disconnected = "NET: --";
        tooltip-format-wifi = "{essid} ({signalStrength}%)\n{ipaddr}";
        tooltip-format-ethernet = "{ifname}\n{ipaddr}";
        tooltip-format-disconnected = "disconnected";
      };

      # --- BAT (hidden if no battery) ---
      "custom/bat" = {
        exec = "${batScript}";
        interval = 30;
        return-type = "plain";
        hide-empty-text = true;
      };

      # --- /: used/total ---
      disk = {
        interval = 60;
        path = "/";
        format = "/: {used}/{total}";
        tooltip = false;
      };

      # --- MEM: used/total ---
      memory = {
        interval = 2;
        format = "MEM: {used}/{total}";
        tooltip = false;
      };

      # --- clock ---
      clock = {
        interval = 30;
        format = "{:%a %F %H:%M}";
        tooltip = false;
      };
    };

    xdg.configFile."waybar/style.css".text = ''
      /* Generated by Home Manager */

      * {
        font-family: "${ui.monoFont.family}";
        font-size: ${toString fontPx}px;
      }

      @define-color fg #${fg};
      @define-color bg #${bg};

      /* ANSI palette (GTK CSS) */
      @define-color c0  #${p 0};
      @define-color c1  #${p 1};
      @define-color c2  #${p 2};
      @define-color c3  #${p 3};
      @define-color c4  #${p 4};
      @define-color c5  #${p 5};
      @define-color c6  #${p 6};
      @define-color c7  #${p 7};
      @define-color c8  #${p 8};
      @define-color c9  #${p 9};
      @define-color c10 #${p 10};
      @define-color c11 #${p 11};
      @define-color c12 #${p 12};
      @define-color c13 #${p 13};
      @define-color c14 #${p 14};
      @define-color c15 #${p 15};

      window#waybar {
        background: @bg;
        color: @fg;
        padding: ${toString vPadPx}px ${toString hPadPx}px;
      }

      #workspaces button.focused {
        border-bottom: 2px solid @c4;
      }

      /* optional: make each module look like a “label: value” block */
      #network, #custom-bat, #disk, #memory, #clock {
        padding: 0 ${toString (px (0.35 * fontPx))}px;
      }
    '';
  };
}
