{ config, lib, pkgs, ui, ... }:

let
  cfg = config.my.wm;

  stripHash = s: lib.removePrefix "#" s;
  p = i: stripHash (builtins.elemAt ui.terminal.palette i);

  bg = stripHash ui.terminal.background;
  fg = stripHash ui.terminal.foreground;
in
{
  /* ============================================================
     Waybar
     ============================================================ */

  config = lib.mkIf (cfg.enable && cfg.bar.enable && cfg.bar.backend == "waybar") {
    my.wm.bar.command = "waybar";

    home.packages = [ pkgs.waybar ];

    xdg.configFile."waybar/config".text = ''
      {
        "layer": "top",
        "position": "${cfg.bar.position}",
        "height": 26,
        "spacing": 8,
        "modules-left": ["sway/workspaces"],
        "modules-center": ["clock"],
        "modules-right": ["cpu", "memory", "pulseaudio", "network", "battery", "tray"]
      }
    '';

    xdg.configFile."waybar/style.css".text = ''
      /* Generated by Home Manager */

      * {
        font-family: "${ui.monoFont.family}";
        font-size: ${toString ui.monoFont.size}px;
      }

      @define-color fg #${fg};
      @define-color bg #${bg};

      /* ANSI palette (GTK CSS) */
      @define-color c0  #${p 0};
      @define-color c1  #${p 1};
      @define-color c2  #${p 2};
      @define-color c3  #${p 3};
      @define-color c4  #${p 4};
      @define-color c5  #${p 5};
      @define-color c6  #${p 6};
      @define-color c7  #${p 7};
      @define-color c8  #${p 8};
      @define-color c9  #${p 9};
      @define-color c10 #${p 10};
      @define-color c11 #${p 11};
      @define-color c12 #${p 12};
      @define-color c13 #${p 13};
      @define-color c14 #${p 14};
      @define-color c15 #${p 15};

      window#waybar {
        background: @bg;
        color: @fg;
      }

      #workspaces button.focused {
        border-bottom: 2px solid @c4;
      }

      #clock {
        padding: 0 10px;
      }
    '';
  };
}
