{ config, lib, pkgs, ui, ... }:

let
  stripHash = s: lib.removePrefix "#" s;

  p = i: stripHash (builtins.elemAt ui.terminal.palette i);

  termBg = stripHash ui.terminal.background;
  termFg = stripHash ui.terminal.foreground;
  termCursor = stripHash ui.terminal.cursor;

in
{
  /* ============================================================
     foot (HM core module)
     ------------------------------------------------------------
     Terminal emulator configuration.
     Consumes my.ui terminal tokens passed via extraSpecialArgs:
       ui.terminal.{background,foreground,cursor,palette}
     ============================================================ */


  /* ============================================================
     Packages
     ============================================================ */

  home.packages = [
    pkgs.foot
  ];


  /* ============================================================
     Config: ~/.config/foot/foot.ini
     ------------------------------------------------------------
     Map UI token ANSI palette (0..15) to foot’s regular/bright.
     UI palette order is canonical:
       0..7   normal  (black..white)
       8..15  bright  (black..white)
     ============================================================ */

  xdg.configFile."foot/foot.ini".text = ''
    # Generated by Home Manager

    [main]
    font=${ui.monoFont.family}:size=${toString ui.monoFont.size}

    [colors]
    foreground=${termFg}
    background=${termBg}
    cursor=${termBg} ${termCursor}

    regular0=${p 0}
    regular1=${p 1}
    regular2=${p 2}
    regular3=${p 3}
    regular4=${p 4}
    regular5=${p 5}
    regular6=${p 6}
    regular7=${p 7}

    bright0=${p 8}
    bright1=${p 9}
    bright2=${p 10}
    bright3=${p 11}
    bright4=${p 12}
    bright5=${p 13}
    bright6=${p 14}
    bright7=${p 15}
  '';
}
